#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

file_name = ARGV[0]
reader = File.open(file_name, 'r')
header = reader.readline
content = reader.readline
fields = header.chomp.split("\t")
columns = content.chomp.split("\t")
width = fields.map { |field| field.length }.max

fields.each_with_index do |field, index|
  printf("%#{width}s: %s\n", field, columns[index])
end

reader.close